'''
Display 3D plots of different surfaces, using matplotlib.

- klein bottle

A Klein bottle is a closed surface with only one side and no boundary. It is a non-orientable surface, meaning that it has no distinct inside and outside. It can be visualized as a bottle with a Möbius strip as its base.

- torus

A torus is a surface of revolution generated by revolving a circle in three-dimensional space about an axis coplanar with the circle.

- saddle

A saddle is a surface with a single maximum and a single minimum. It is a non-orientable surface, meaning that it has no distinct inside and outside.

- bowl

A bowl is a surface of revolution generated by revolving a circle in three-dimensional space about an axis coplanar with the circle.

- wave

A wave is a disturbance that propagates through space or a medium, transferring energy from one point to another.

- fedora

A Fedora plot is a graph of a function of two variables, where the x and y coordinates are the variables and the z coordinate is the value of the function.

'''

import numpy as np
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

# --- functions ---
# reference: https://mathworld.wolfram.com/KleinBottle.html

def klein_bottle(u, v):
    x=(-2/15)*np.cos(u)*(3*np.cos(v)-30*np.sin(u)+90*np.power(np.cos(u),4)*np.sin(u)-60*np.power(np.cos(u),6)*np.sin(u)+5*np.cos(u)*np.cos(v)*np.sin(u))
    t1=3*np.cos(v)-3*np.cos(u)*np.cos(u)*np.cos(v)-48*np.power(np.cos(u),4)*np.cos(v)+48*np.power(np.cos(u),6)*np.cos(v)-60
    y=-1/15*np.sin(u)*(t1*np.sin(u)+5*np.cos(u)*np.cos(v)*np.sin(v)-5*np.power(np.cos(u),3)*np.cos(v)*np.sin(u)-80*np.power(np.cos(u),5)*np.cos(v)*np.sin(u)+80*np.power(np.cos(u),7)*np.cos(v)*np.sin(u))
    z=(2/15)*(3+5*np.cos(u)*np.sin(u))*np.sin(v)
    return x, y, z

# reference: https://mathworld.wolfram.com/Torus.html
def torus(u,v):
    r = 1
    b = 3
    x = (r*np.cos(u)+b)*np.cos(v)
    y = (r*np.cos(u)+b)*np.sin(v)
    z = (r*np.sin(u))
    return x, y, z

# reference: https://mathworld.wolfram.com/Saddle.html
def saddle(x,y):
    z = np.power(x,2)-np.power(y,2)
    return x, y, z

# reference: https://mathworld.wolfram.com/Bowl.html
def bowl(x,y):
    z = np.power(x,2)+np.power(y,2)
    return x, y, z

# reference: https://mathworld.wolfram.com/Wave.html
def wave(x,y):
    z = np.cos(x)+np.sin(y)
    return x, y, z

# reference: https://mathworld.wolfram.com/Fedora.html
def fedora(x,y):
    d = np.power(x,2)+np.power(y,2)
    z=np.sin(d/10)
    return x, y, z

# --- main ---
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, 2* np.pi, 100)

#u = np.linspace(-10, 10, 100)
#v = np.linspace(-10, 10, 100)

u, v = np.meshgrid(u, v)

print("chooe a surface")
print("1. Klein bottle")
print("2. Torus")
print("3. Saddle")
print("4. Bowl")
print("5. Wave")
print("6. Fedora")

choice = int(input("Enter your choice: "))

if choice == 1:
    x,y,z= klein_bottle(u, v)
elif choice == 2:
    x,y,z= torus(u, v)
elif choice == 3:
    x,y,z= saddle(u, v)
elif choice == 4:
    x,y,z= bowl(u, v)
elif choice == 5:
    x,y,z= wave(u, v)
elif choice == 6:
    x,y,z= fedora(u, v)

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})

ax.plot_surface(x, y, z,
                 rstride=1, cstride=1,
                 cmap=plt.get_cmap('cool'),
                 linewidth=0, antialiased=False)

plt.show()
